training:
  project_name: images_seg
  train_name: unet-6.5.3xm_aug
  seed: 1702
  epochs: 30
  batch: 64
  lr: 3e-5
  model_path: ${hydra:run.dir}/weights
  wandb_path: ${hydra:run.dir}/wandb
  save_best_of: 3
  checkpoint_monitor: val_loss
  early_stopping_patience: 9
  num_image_to_save: 4
  mask_border: 0.35

data:
  data_directory: dataset/dataset2
  height: 300
  width: 300
  flip_probability: 0.2
  brightness_probability: 0.1