training:
  project_name: images_seg_3
  train_name: unet-1
  seed: 1702
  epochs: 30
  batch: 16
  lr: 3e-5
  model_path: ${hydra:run.dir}/weights
  wandb_path: ${hydra:run.dir}/wandb
  save_best_of: 3
  checkpoint_monitor: val_loss
  early_stopping_patience: 9
  num_image_to_save: 4
  mask_border: 0.3

data:
  data_directory: dataset/dataset3
  height: 1000
  width: 1400
  flip_probability: 0.2
  brightness_probability: 0.1